global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Store.Domain.Commands.UserCommands;
global using Store.Domain.Entities.User;
global using Store.Domain.Enums;
global using Store.Domain.ValueObjects;
global using Store.Domain.Handlers.UserHandlers;
global using Store.Shared.Commands;
global using Store.Tests.Repositories;
global using Store.Tests.Services;
